apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apiservers.appscode.refat.dev
spec:
  group: appscode.refat.dev
  scope: Namespaced
  names:
    kind: Apiserver
    plural: apiservers
    singular: apiserver
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                port:
                  type: integer
                  minimum: 1
                  maximum: 65535
              required:
                  - image
                  - replicas
                  - port
